### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Bradleykingz** [inoda/ontrack#1]
Request to edit README with installation instructions for someone with zero Ruby experience.

**Comment by inoda** [comment]
@Bradleykingz I will add install instructions today!

**Comment by inoda** [comment]
@Bradleykingz I've added installation steps using [homebrew](https://brew.sh/)

Could you give them a try and close this issue assuming it goes smoothly?

**Comment by inoda** [comment]
@Bradleykingz Just fyi - I have updated the previous documentation. Installation and server starting are now wrapped in a `make` command. Let me know how it goes!

**Comment by inoda** [comment]
Edit - switched to a bash script due to some constraints of Make

**Comment by inoda** [comment]
@Bradleykingz Closing this out, feel free to open it back up if you run into issues!

**Comment by Bradleykingz** [comment]
Thanks for the help! I'm actually on Ubuntu, but the new docs have nudged me in the right direction and I finally got it up and running.

Can create a PR with the Ubuntu installation instructions?

**Comment by inoda** [comment]
@Bradleykingz Yes, that'd be wonderful!
