### ISSUE TITLE
Cannot deploy to heroku

### ISSUE THREAD

**Issue by paxpelus** [inoda/ontrack#15]
I am trying to use the 'Deploy to Heroku' button but after I add my app name and start deployment I am getting the following errors

` Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
			Detected buildpacks: Ruby,Node.js
			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
-----> Ruby app detected
-----> Installing bundler 2.0.2
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.5
-----> Installing dependencies using bundler 2.0.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/............
       Your bundle is locked to puma (3.12.3), but that version could not be found in
       any of the sources listed in your Gemfile. If you haven't changed sources, that
       means the author of puma (3.12.3) has removed it. You'll need to update your
       bundle to a version other than puma (3.12.3) that hasn't been removed in order
       to install.
       Bundler Output: The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/............
       Your bundle is locked to puma (3.12.3), but that version could not be found in
       any of the sources listed in your Gemfile. If you haven't changed sources, that
       means the author of puma (3.12.3) has removed it. You'll need to update your
       bundle to a version other than puma (3.12.3) that hasn't been removed in order
       to install.
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed`

**Comment by inoda** [comment]
@paxpelus Sorry about this, and thank you for opening this issue! This must be from recent PRs I merged from dependabot. I will fix this in the next few days and ping you here when it should be ready to deploy!

**Comment by inoda** [comment]
@paxpelus This should be fixed now!

**Comment by paxpelus** [comment]
@inoda thanks for your help - all works now
