### ISSUE TITLE
Heroku Login Credentials?

### ISSUE THREAD

**Issue by aarif4** [inoda/ontrack#17]
Hi,

When I deploy **ontrack** to Heroku, what're my login credentials? Sorry, I'm pretty new to Heroku.

**Comment by inoda** [comment]
@aarif4 I have no idea what you're login credentials are. You need to sign up for a free Heroku account first. If you've already done that then use their account/password recovery to figure out your credentials.

**Comment by aarif4** [comment]
Hi,

I understand that I need to setup a free Heroku account first. I've been able to do that successfully. However, once I clicked the "Deploy to Heroku"link in your **README.md**, I noticed that everything was being installed automatically. As a result, I didn't have to manually create a user. So I'm assuming that a default username/password combination was defined. 

So now every time I access my **ontrack** instance in my Heroku account, I'm greeted with a login screen. Given that I haven't created a user throughout the installation process, I don't know what credentials to use. I tried using `admin`/`admin` but that didn't work. I tried keeping both fields empty and that didn't work either. 

Do you know what the default username/password would be on an **ontrack** instance that was deployed using Heroku?

**Comment by inoda** [comment]
@aarif4 Read the sections "Creating a user" and "Hosting your own" in the readme
