### ISSUE TITLE
Plaid Integration

### ISSUE THREAD

**Issue by LukeStaszewski** [inoda/ontrack#25]
Hello!

I love this app - fantastic work on it. It's awesome. Thank you for sharing it.

I love the idea of self hosting and being in control of your data - and I know what I'm about to suggest would potentially put some of your data in the hands of a third party, but perhaps it's something to be considered, depending on Plaids T&C? I am not super educated with them, but I do use them for my business finance software and you can use their API for free in small amounts, enough for most people. It connects to your bank and transfers in the data via API supposedly securely.

Might be a good idea to have this as an option in the app? If you have multiple bank accounts and credit cards, it can be a pain to log in (and go through all the security processes) and then export a CSV and import it in. I know some people won't mind doing this, but the lure of just being able to log into this one, self hosted app and immediately see all the information in all your accounts is quite a powerful feature that  makes the whole process less painful.

I hope in the future there is an open source and transparent API for connecting to banks etc securely, but as far as I know, Plaid is the best option right now. Love to hear your thoughts

**Comment by inoda** [comment]
@LukeStaszewski 

> I know what I'm about to suggest would potentially put some of your data in the hands of a third party

This is what would stop me from pulling in Plaid. One of the main reasons I built this tool is that I did not want to use an app where I had to connect my bank account.

That being said, a Plaid integration could be added to OnTrack where it is optional/opt-in. I have no plans of working on that any time soon. Maybe it's something you could contribute to the project if you're interested?

One other thing I'd like to call out is that if the main pain point is combing CSV exports, I wrote a little script for myself to format my bank's export to be easier to work with: https://github.com/inoda/ontrack/blob/master/lib/csv_helper.rb. I imagine it wouldn't be a ton of work to create a script that reformats/combines exports from multiple sources. I understand this is still way more manual than a bank API integration.

**Comment by inoda** [comment]
@LukeStaszewski Also, my understanding is that Plaid's integration works by storing your login info and literally programmatically logging into your bank account (see https://security.stackexchange.com/questions/198005/is-plaid-a-service-which-collects-user-s-banking-login-information-safe-to-use). Not sure if this is still the implementation but I wouldn't be comfortable with such a solution.

**Comment by LukeStaszewski** [comment]
Hey @inoda thanks a ton for getting back to me on this. I totally understand your apprehensions with it. I believe Plaid connects by the best available way for the specific company. I.e sometimes I think they do programmatically login if there is no API available, but if there is an API provided by the bank, as is the case with most modern banks, they do it that way. Still, it's not ideal for them to be storing the API keys.

In theory long term I guess I could make a script that stores the credentials encrypted locally and logs in / connects directly to the API, but for the banks which do not have an official API I think this kind of usage negates their terms and conditions unless its done through an official partner like Plaid. I will have to explore it further.

I would be happy to try to implement Plaid as an optional feature as an intermediary step for those of us who don't mind sacrificing a bit of privacy for convenience sake until a better solution is available, with a big fat disclaimer as well of course. Obviously the end goal is to completely be rid of third parties but I think as long as people are aware of what they are doing it could be a decent partial solution.

Thank you for sharing the CSV github, that definitely does make it easier but for me personally I am willing to sacrifice the privacy for the convenience (god I hate to say that - but its unfortunately true haha). I use Yolt at the moment and its just so damn easy to check all your accounts at once, any time. 

I'm not the most talented programmer but I will give it a shot. I will try my best to be security conscious but perhaps before we merge it into the main project we should try to find a friendly neighbourhood security expert to take a peek at it haha.

**Comment by inoda** [comment]
@LukeStaszewski Also want to call out that this:

> I use Yolt at the moment and its just so damn easy to check all your accounts at once, any time.

The purpose of this app is mainly for tracking expenses and budgeting, not checking account balances. Slight nuance..anyways, sounds good!
