### ISSUE TITLE
Creating username and password for docker-compose up.

### ISSUE THREAD

**Issue by ozzutest** [inoda/ontrack#41]
Hello, I'm struggling with creating account in docker. I don't know how to solve this issue.
What I've tried is creating manually user and password using:
<code>
bundle exec rails c
</code>

and 

<code>
User.create!(username: "...", password: "...")
</code>
After above operations, tried to migrate database, but it didn't work. I know it should be done at docker-compose command, but i don't know what is the command. 
Also I tried this from documentation describing deploy on Heroku:
<code>
docker-compose run bundle exec rails c 
</code>

**Comment by hleonps** [comment]
Hi, have you tried to execute the command inside the container? https://docs.docker.com/engine/reference/commandline/exec/

As you are using Docker (docker-compose is just a tool to orchestrate) you need to run the Rails commands inside the container. First you need to get the container ID which you can get with `docker ps` (run `docker-compose up` first). The image suffix is `_app`, so look up for a container with that image (ex `ontrack_app`).

Then run:

`docker exec -it [CONTAINER-ID-HERE] bundle exec rails c`

It should open a new shell in which you can interact with Rails inside the container. Run `User.create!(username: "...", password: "...")` and you should be okay to go. Now you can open `localhost:3000` and log in with the new user.

**Comment by Samuel-Martineau** [comment]
I also tried this, but I got an error (it was a few weeks ago, so I don’t remember what is was)...
