### ISSUE TITLE
Heroku build fails. 

### ISSUE THREAD

**Issue by dotbm** [inoda/ontrack#44]
The Heroku build fails due to the package using ruby-2.6.5.

Log:

-----> Building on the Heroku-20 stack

 !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.

			Detected buildpacks: Ruby,Node.js

			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order

-----> Ruby app detected

-----> Installing bundler 2.1.4

-----> Removing BUNDLED WITH version in the Gemfile.lock

-----> Compiling Ruby/Rails

       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.5.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.

       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.5.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.

 !

 !     The Ruby version you are trying to install does not exist on this stack.

 !     

 !     You are trying to install ruby-2.6.5 on heroku-20.

 !     

 !     Ruby ruby-2.6.5 is present on the following stacks:

 !     

 !     - cedar-14

 !     - heroku-16

 !     - heroku-18

 !     

 !     Heroku recommends you use the latest supported Ruby version listed here:

 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

 !     

 !     For more information on syntax for declaring a Ruby version see:

 !     https://devcenter.heroku.com/articles/ruby-versions

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed

**Comment by inoda** [comment]
@dotbm Hey there. I just bumped to ruby 2.6.6 which resolved the issue. Thanks for flagging this!
