### ISSUE TITLE
Disabling FORCE_SSL in production rails when on docker

### ISSUE THREAD

**Issue by kominoshja** [inoda/ontrack#46]
When you run the docker container with rails on production, the app tries to run on SSL, but since there's no way to configure the cert, it makes the app unusable.

I would suggest editing entrypoint.sh so that FORCE_SSL is disabled. Or am I missing something?

**Comment by inoda** [comment]
@salquier @luketainton Do y'all have any thoughts on this?

**Comment by luketainton** [comment]
@kominoshja That is actually set using an environment variable [here](https://github.com/inoda/ontrack/blob/29980d67eaa528e1398cfc60e6ecb4f7fabde9fb/config/environments/production.rb#L47) - you can override the variable. If you're using Docker you can use `-e FORCE_SSL=false`.

**Comment by inoda** [comment]
@luketainton thanks!!

**Comment by kominoshja** [comment]
@luketainton @inoda thanks! I had tried to set it in the docker-compose but it didn't seem to want to apply it from there. Only when I changed the file itself would it apply. Any thoughts as to why that is?

**Comment by luketainton** [comment]
@kominoshja That's a strange one, it should apply it from the compose file and failover to false if it's not set. @inoda any ideas?

**Comment by kominoshja** [comment]
@luketainton Maybe we should reopen this? Seems like @inoda has missed your ping :/

**Comment by luketainton** [comment]
@kominoshja I can help with Docker but I have no experience in Ruby so I'm afraid I can't help on that part. @inoda do you have any ideas here?
