### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [inoda/ontrack#78]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@j-gainsec) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by inoda** [comment]
@JamieSlome Feel free to just share the issue here.

**Comment by JamieSlome** [comment]
@inoda - sure, both issues can be found here:

https://huntr.dev/bounties/31284e3a-ed7b-4896-817d-8d340f4d3862/
https://huntr.dev/bounties/dbbf87f0-d77b-4b1b-a28f-6d8ef424e8f0/

Both are currently private and only accessible by you 👍

**Comment by inoda** [comment]
@JamieSlome Can you just share the issue here publicly? I understand this is a mechanism to get adoption for your site but I'm not interested in making an account

**Comment by inoda** [comment]
Seems like this got moved to #82

**Comment by JamieSlome** [comment]
@inoda - I have made both reports public at the same URLs. 

We do not make reports private for adoption, but purely because many maintainers don't want reports public by default. We allow maintainers to access reports using magic URLs, where sign-up is not required at all. This is why we first request an e-mail, so we can send a magic URL to view the reports 👍
